# Task :  1

### Q1 :- Print the given strings as per stated format.

**Given strings**:
```
"Data" "Science" "Learning" "Task"
"By" "Python"
```
**Output**:
```
Data-Science-Learning-Task-started-By-Python
```

Concept- [Seperator and End]

In [15]:
# Write your code here
print("Data","Science","Learning","Task",sep='-',end='-started-')
print("By","Python",sep='-')

Data-Science-Learning-Task-started-By-Python

### Q2:- Write a program that will convert celsius value to fahrenheit.

In [ ]:
# Write your code here
celcius = float(input('enter the temp in celcius'))

faren = celcius * (9/5) + 32

print(faren,'F')

enter the temp in celcius44
111.2 F

### Q3:- Take 2 numbers as input from the user.Write a program to swap the numbers without using any special python syntax.

In [ ]:
# Write your code here

a = 6
b = 9

temp = a
a = b
b = temp

print(a)
print(b)

9
6

### Q4:- Write a program to find the euclidean distance between two coordinates.Take both the coordinates from the user as input.

In [ ]:
# Write your code here

p1x = int(input('enter x cood of 1st point'))
p1y = int(input('enter y cood of 1st point'))
p2x = int(input('enter x cood of 2nd point'))
p2y = int(input('enter y cood of 2nd point'))

distance = ((p2x - p1x)**2 + (p2y - p1y)**2)**0.5

print(round(distance,2))

enter x cood of 1st point1
enter y cood of 1st point1
enter x cood of 2nd point5
enter y cood of 2nd point6
6.4

### Q5:- Write a program to find the simple interest when the value of principle,rate of interest and time period is provided by the user.

In [ ]:
# Write your code here
p = int(input('Enter amount'))
t = int(input('Enter time period'))
r = float(input('Enter rate'))

interest = (p*t*r)/100

print('the interest is',interest)

Enter amount500
Enter time period3
Enter rate4
the interest is 60.0

### Q6:- Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.

For example:
Input:
heads -> 4
legs -> 12
<br>
Output:
dogs -> 2
chicken -> 2

In [ ]:
# Write your code here
# Input the number of heads and legs
heads = int(input("Enter the total number of heads: "))
legs = int(input("Enter the total number of legs: "))

# Calculate the number of chickens and dogs
chickens = (legs - 2 * heads) // 2
dogs = heads - chickens

# Output the result or error message based on the validity
result = f"Dogs: {dogs}, Chickens: {chickens}"

print(result)

Enter the total number of heads: 4
Enter the total number of legs: 12
Dogs: 2, Chickens: 2

### Q7:- Write a program to find the sum of squares of first n natural numbers where n will be provided by the user.

In [ ]:
# Write your code here
n = int(input('enter the number'))

result = (n*(n+1)*(2*n + 1))/6
print(result)

enter the number4
30.0

### Q8:- Given the first 2 terms of an Arithmetic Series.Find the Nth term of the series. Assume all inputs are provided by the user.

In [ ]:
# Write your code here
first_term = int(input('enter 1st term'))
second_term = int(input('enter 2nd term'))
n = int(input('enter the value of n'))

d = second_term - first_term

an = first_term + (n-1)*d

print(an)

enter 1st term6
enter 2nd term2
enter the value of n5
-10

### Q9:- Given 2 fractions, find the sum of those 2 fractions.Take the numerator and denominator values of the fractions from the user.

In [ ]:
# Write your code here
n1 = int(input('first num'))
d1 = int(input('first den'))
n2 = int(input('second num'))
d2 = int(input('second den'))

rn = n1*d2 + n2*d1
rd = d1*d2

print('{}/{}'.format(rn,rd))

first num5
first den6
second num2
second den4
32/24

### Q10:- Given the height, width and breadth of a milk tank, you have to find out how many glasses of milk can be obtained? Assume all the inputs are provided by the user.



Input:<br>
Dimensions of the milk tank<br>
H = 20cm, L = 20cm, B = 20cm
<br><br>
Dimensions of the glass<br>
h = 3cm, r = 1cm

In [ ]:
# Write your code here
import math
ht = float(input('height'))
bt = float(input('breadth'))
lt = float(input('length'))


hg = float(input('heaight of glass'))
rg = float(input('radius of glass'))


vtank = ht*bt*lt
vglass = 3.14*rg*rg*hg

print('no of glasses is',math.floor(vtank/vglass))

height20
breadth13
length10
heaight of glass5
radius of glass3
no of glasses is 18